import { formatRupees } from "./Scoreboard";

export default function MessagePreviewModal({ action, onClose }) {
  if (!action) return null;
  return (
    <div className="fixed inset-0 bg-ink-950/80 backdrop-blur-sm z-[60] flex items-center justify-center p-4" onClick={onClose}>
      <div className="w-full max-w-sm bg-white rounded-2xl overflow-hidden shadow-2xl" onClick={(e) => e.stopPropagation()}>
        <div className="bg-ink-900 px-4 py-3 flex items-center justify-between">
          <span className="text-xs font-mono text-text-muted">Customer notification preview</span>
          <button onClick={onClose} className="text-text-faint hover:text-white text-lg leading-none">&times;</button>
        </div>
        <div className="p-5">
          <p className="text-sm font-semibold text-gray-900 mb-2">Payment unsuccessful</p>
          <p className="text-sm text-gray-700 leading-relaxed mb-4">{action.message}</p>
          <a
            href={action.payment_link_url}
            target="_blank"
            rel="noreferrer"
            className="block w-full text-center rounded-lg bg-recovery text-ink-950 text-sm font-semibold py-2.5"
          >
            Complete Payment — {formatRupees(action.subscription_amount)}
          </a>
        </div>
        <div className="bg-gray-50 px-5 py-3 flex items-center justify-between border-t border-gray-200">
          <span className="text-[10px] text-gray-500">Generated by MandateIQ &middot; Fallback action</span>
          {action.message_verified ? (
            <span className="text-[10px] font-mono text-recovery">✓ verified</span>
          ) : (
            <span className="text-[10px] font-mono text-fail">unverified</span>
          )}
        </div>
      </div>
    </div>
  );
}
